Stripovi.Web/Pages/Administrator.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stripovi.Web.MockData.MockKontaktRepository;
using Stripovi.Web.MockData.MockPorudzbinaRepository;
using Stripovi.Web.MockData.MockStripRepository;

namespace Stripovi.Web.Pages
{
    [Authorize(Roles = "SuperAdmin")]
    public class AdministratorModel : PageModel
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly IStripRepository stripRepository;
        private readonly IPorudzbinaRepository porudzbinaRepository;
        private readonly IKontaktRepository kontaktRepository;

        public AdministratorModel(UserManager<IdentityUser> userManager,
                          IStripRepository stripRepository,
                          IPorudzbinaRepository porudzbinaRepository,
                          IKontaktRepository kontaktRepository)
        {
            this.userManager = userManager;
            this.stripRepository = stripRepository;
            this.porudzbinaRepository = porudzbinaRepository;
            this.kontaktRepository = kontaktRepository;
        }
        public int brojRegistrovanihClanova { get; set; }
        public int brojPorudzbina { get; set; }
        public int brojStripova { get; set; }
        public int brojPoruka { get; set; }
        public void OnGet()
        {
            brojRegistrovanihClanova = userManager.Users.Count();
            brojPorudzbina = porudzbinaRepository.GetPorudzbine().Result.Count();
            brojStripova = stripRepository.GetStripove().Result.Count();
            brojPoruka = kontaktRepository.brojPoruka();
        }
    }
}

Stripovi.Web/Pages/Administrator/Kontakti/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Stripovi.Web.Areas.Identity.Data;
using Stripovi.Web.MockData;

namespace Stripovi.Web.Pages.Administrator.Kontakti
{
    [Authorize(Roles = "SuperAdmin")]
    public class DeleteModel : PageModel
    {
        private readonly UserDbContext _context;

        public DeleteModel(UserDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Kontakt Kontakt { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Kontakt = await _context.Kontakt.FirstOrDefaultAsync(m => m.Id == id);

            if (Kontakt == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Kontakt = await _context.Kontakt.FindAsync(id);

            if (Kontakt != null)
            {
                _context.Kontakt.Remove(Kontakt);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Stripovi.Web/Pages/Administrator/Kontakti/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Stripovi.Web.Areas.Identity.Data;
using Stripovi.Web.MockData;

namespace Stripovi.Web.Pages.Administrator.Kontakti
{
    [Authorize(Roles = "SuperAdmin")]
    public class DetailsModel : PageModel
    {
        private readonly UserDbContext _context;

        public DetailsModel(UserDbContext context)
        {
            _context = context;
        }

        public Kontakt Kontakt { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Kontakt = await _context.Kontakt.FirstOrDefaultAsync(m => m.Id == id);

            if (Kontakt == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Stripovi.Web/Pages/Administrator/Kontakti/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Stripovi.Web.Areas.Identity.Data;
using Stripovi.Web.MockData;

namespace Stripovi.Web.Pages.Administrator.Kontakti
{
    [Authorize(Roles = "SuperAdmin")]
    public class IndexModel : PageModel
    {
        private readonly UserDbContext _context;

        public IndexModel(UserDbContext context)
        {
            _context = context;
        }

        public IList<Kontakt> Kontakt { get;set; }

        public async Task OnGetAsync()
        {
            Kontakt = await _context.Kontakt.ToListAsync();
        }
    }
}

Stripovi.Web/Pages/Administrator/Porudzbine/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stripovi.Web.Areas.Identity.Data;
using Stripovi.Web.MockData;

namespace Stripovi.Web.Pages.Administrator.Porudzbine
{
    public class CreateModel : PageModel
    {
        private readonly UserDbContext _context;

        public CreateModel(UserDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return Page();
        }

        [BindProperty]
        public Porudzbina Porudzbina { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Porudzbina.Add(Porudzbina);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Stripovi.Web/Pages/Administrator/Porudzbine/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Stripovi.Web.Areas.Identity.Data;
using Stripovi.Web.MockData;

namespace Stripovi.Web.Pages.Administrator.Porudzbine
{
    [Authorize(Roles = "SuperAdmin")]
    public class DeleteModel : PageModel
    {
        private readonly UserDbContext _context;

        public DeleteModel(UserDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Porudzbina Porudzbina { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Porudzbina = await _context.Porudzbina
                .Include(p => p.User).FirstOrDefaultAsync(m => m.IdPorudzbine == id);

            if (Porudzbina == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Porudzbina = await _context.Porudzbina.FindAsync(id);

            if (Porudzbina != null)
            {
                _context.Porudzbina.Remove(Porudzbina);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Stripovi.Web/Pages/Index.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Stripovi.Web.MockData;
using Stripovi.Web.MockData.MockKorpaRepository;
using Stripovi.Web.MockData.MockPorudzbinaRepository;
using Stripovi.Web.MockData.MockStripRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace Stripovi.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly IStripRepository stripRepository;
        private readonly IKorpaRepository korpaRepository;
        private readonly IMapper mapper;
        private readonly IPorudzbinaRepository porudzbinaRepository;

        public IndexModel(ILogger<IndexModel> logger,
                          SignInManager<IdentityUser> signInManager,
                          IStripRepository stripRepository,
                          IKorpaRepository korpaRepository,
                          IMapper mapper,
                          IPorudzbinaRepository porudzbinaRepository)
        {
            _logger = logger;
            this.signInManager = signInManager;
            this.stripRepository = stripRepository;
            this.korpaRepository = korpaRepository;
            this.mapper = mapper;
            this.porudzbinaRepository = porudzbinaRepository;
        }

        public IEnumerable<Strip> Stripovi { get; set; }

        [BindProperty]
        public int IdStripaZaKorpu { get; set; }

        public string Search { get; set; }

        public int brojStripovauProdaji { get; set; }

        public async Task<IActionResult> OnGetAsync()
        { 
            if (signInManager.IsSignedIn(User))
            {
                if (User.IsInRole("SuperAdmin"))
                {
                  return RedirectToPage("Administrator");
                }
                var ulogvanUser = signInManager.UserManager.GetUserId(User);

                Stripovi = await stripRepository.UserStripoviVanKorpe(ulogvanUser);
                
            }
            else
            {
              Stripovi = await stripRepository.GetStripove();
            }
            brojStripovauProdaji = Stripovi.Count();

            return Page();
            //  Stripovi = await stripoviService.GetStripove();  //1
        }



        public async Task<IActionResult> OnPostAsync()
        {
            if (signInManager.IsSignedIn(User))
            {
                string ulogvanUser = signInManager.UserManager.GetUserId(User);
                int brojPorudzbina = porudzbinaRepository.GetPorudzbine().Result.Where(e => e.UserId == ulogvanUser).Count();

                if(brojPorudzbina < 3)
                {
                    var strip = await stripRepository.GetStrip(IdStripaZaKorpu);

                    if(strip != null)
                    {
                        Korpa novaKorpa = new Korpa();
                        novaKorpa = mapper.Map(strip, novaKorpa);
                        novaKorpa.UserId = ulogvanUser;
                    
                        await korpaRepository.AddKorpa(novaKorpa);
                        return RedirectToAction("OnGetAsync");
                    }
                    TempData["error"] = "Strip nije pronadjen!";
                    return RedirectToAction("OnGetAsync");
                }
                else
                {
                    TempData["error"] = "Maksimalni broj porudzbina je 3!";
                    return RedirectToAction("OnGetAsync");
                }

            }
            TempData["message"] = "Mora te se ulogovati pre nego sto izvrsite porudzbinu!";
            return Redirect("/Identity/Account/Login");
        }

        public async Task<IActionResult> OnPostSearch(string Search)
        {
            string ulogvanUser = signInManager.UserManager.GetUserId(User);

            if (Search != null)
            {
                Stripovi = await stripRepository.Search(Search, ulogvanUser);
                brojStripovauProdaji = Stripovi.Count();
                return Page();
            }
            Stripovi = await stripRepository.UserStripoviVanKorpe(ulogvanUser);
            brojStripovauProdaji = Stripovi.Count();
            return Page();
        }
    }
}

Stripovi.Web/Pages/Korpa.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stripovi.Web.MockData;
using Stripovi.Web.MockData.MockKorpaRepository;
using Stripovi.Web.MockData.MockPorudzbinaRepository;
using Stripovi.Web.MockData.MockStripRepository;

namespace Stripovi.Web.Pages
{
    [Authorize]
    public class KorpaModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly IKorpaRepository korpaRepository;
        private readonly IPorudzbinaRepository porudzbinaRepository;

        public KorpaModel(SignInManager<IdentityUser> signInManager,
                          IKorpaRepository korpaRepository,
                          IPorudzbinaRepository porudzbinaRepository)
        {
            this.signInManager = signInManager;
            this.korpaRepository = korpaRepository;
            this.porudzbinaRepository = porudzbinaRepository;
        }
        public int IdStripaObrisi { get; set; }
        public int UkupnaCena { get; set; }
        public InputBuyConfirmed BuyConfirmed { get; set; }
        public IEnumerable<Korpa> StripoviuKorpi { get; set; }

        public class InputBuyConfirmed
        {
            [Required(ErrorMessage = "Niste upisali Grad!")]
            public string Grad { get; set; }

            [Required(ErrorMessage = "Niste upisali Postanski broj!")]
            [Display(Name = "Postanski Broj")]
            public int? PostanskiBroj { get; set; }

            [Required(ErrorMessage = "Niste upisali Ulicu!")]
            public string Ulica { get; set; }

            [Required(ErrorMessage = "Niste upisali Kucni Broj!")]
            [Display(Name = "Kucni Broj")]
            public string KucniBroj { get; set; }
            public string Placanje { get; set; }
            public string Pitanje { get; set; }
            [Required]
            [Range(typeof(bool), "true", "true", ErrorMessage = "Nisi stiklirao!")]
            public bool SlozenSaUslovima { get; set; }
            public List<int> IdPorucenihStripova { get; set; }
            public int UkupnaCena { get; set; }
        }
        private async Task GetSveInformacije()
        {
            string ulogvanUser = signInManager.UserManager.GetUserId(User);

            var stripoviuKorpi = await korpaRepository.UserStripoviuKorpi(ulogvanUser);

            int ukupnaCena = 0;

            foreach (var item in stripoviuKorpi)
            {
                ukupnaCena += item.Cena;
            }

            UkupnaCena = ukupnaCena;
            StripoviuKorpi = stripoviuKorpi;
        }
        //-----------------------------------------OnGet------------------------------------------------
        public async Task OnGet()
        {
            await GetSveInformacije();
        }
        //-----------------------------------------OnPostObrisi------------------------------------------------
        public async Task OnPostObrisi(int IdStripaObrisi)
        {
            var selektovanStripuKorpi = await korpaRepository.GetKorpa(IdStripaObrisi);

            if (selektovanStripuKorpi != null)
            {
                var result = await korpaRepository.DeleteStripUKorpi(selektovanStripuKorpi.IdStripa);
                if (result == null)
                {
                    NotFound();
                }
                TempData["message"] = "Strip je obrisan iz korpe!";
                await GetSveInformacije();
            }
            await GetSveInformacije();
        }

        //-----------------------------------------OnPostPostvrdi------------------------------------------------
        public async Task<IActionResult> OnPostPotvrdi(InputBuyConfirmed BuyConfirmed)
        {
            if (ModelState.IsValid)
            {
                string userId = signInManager.UserManager.GetUserId(User);

                Porudzbina porudzbina = new Porudzbina
                {
                    UserId = userId,
                    VremePosiljke = DateTime.Now,
                    BrojPorucenihStripova = BuyConfirmed.IdPorucenihStripova.Count,
                    Pitanje = BuyConfirmed.Pitanje,
                    Grad = BuyConfirmed.Grad,
                    KucniBroj = BuyConfirmed.KucniBroj,
                    Placanje = BuyConfirmed.Placanje,
                    UkupnaCena = BuyConfirmed.UkupnaCena,
                    Ulica = BuyConfirmed.Ulica,
                    PostanskiBroj = BuyConfirmed.PostanskiBroj.Value,
                    Status = "Pakovanje"
                };
                await porudzbinaRepository.AddPorudzbinu(porudzbina, BuyConfirmed.IdPorucenihStripova);
                await korpaRepository.DeleteSveUKorpi(userId);
                TempData["message"] = "Uspesno ste izvrsili porudzbinu!";
                return RedirectToPage("Index");
            }

            await GetSveInformacije();
            return Page();
        }
    }
}

Stripovi.Web/Pages/Administrator.cshtml
@page
@model Stripovi.Web.Pages.AdministratorModel
@{
}

<style>
    .karta-stats {
        padding-top: 1em;
    }

    .plava {
        border-left: 10px solid;
        border-left-color: dodgerblue;
    }

    .zuta {
        border-left: 10px solid;
        border-left-color: orange;
    }

    .zelena {
        border-left: 10px solid;
        border-left-color: forestgreen;
    }

    .crvena {
        border-left: 10px solid;
        border-left-color: red;
    }

    h6 {
        margin-top: -20px;
        font-weight: bold;
    }
    .karta-funkcija {
        padding-top: 1em;
    }
    .card {
        background-color: #53354A;
    }
    .card-header {
        background-color: #903749;
    }
    .komande{
        display:flex;
        flex-direction:column;
        width: 10em;
        margin: auto;
    }
    .komande a{
        margin-top: 1em;
    }
</style>
<div class="text-center">
        <h1 class="display-4"><b>Glavni interfejs</b></h1>
        <h4> <b style="color:red">ZA ADMINE</b></h4>
        <hr />
</div>
    <div class="row">
        <div class="col-sm-4">
            <div class="karta-stats">
                <div class="card plava shadow rounded">
                    <div class="card-body">
                        <h6 class="card-title" style="color:dodgerblue">
                            Broj Registrovanih Clanova
                        </h6>
                        <h4>@Model.brojRegistrovanihClanova</h4>
                    </div>
                </div>
            </div>
            <div class="karta-stats">
                <div class="card zuta shadow rounded">
                    <div class="card-body">
                        <h6 class="card-title" style="color:orange">
                            Broj Porudzbina
                        </h6>
                        <h4>@Model.brojPorudzbina</h4>
                    </div>
                </div>
            </div>
            <div class="karta-stats">
                <div class="card zelena shadow rounded">
                    <div class="card-body">
                        <h6 class="card-title" style="color:forestgreen">
                            Broj Stripova u Prodaji
                        </h6>
                        <h4>@Model.brojStripova</h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-8 karta-funkcija">
            <div class="card text-center shadow rounded" style="padding-bottom:52px;">
                <div class="card-header">
                    <h3>Funkcije</h3>
                </div>
                <div class="card-body">
                    <div class="komande" style="padding-top:10px">
                        <a class="btn btn-success" asp-page="administrator/stripovi/create/">
                            <svg width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                            </svg>
                        Registruj Strip</a>
                        <a class="btn btn-primary" asp-page="Administrator/Stripovi/Index">Stripovi</a>
                        <a class="btn btn-primary" asp-page="Administrator/Porudzbine/Index">Porudzbine</a>
                        <a class="btn btn-warning" asp-page="administrator/kontakti/Index">Sanduce <span class="badge badge-light">@Model.brojPoruka</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

Stripovi.Web/Pages/Korpa.cshtml
@page
@model Stripovi.Web.Pages.KorpaModel
@{
    ViewData["Title"] = "Korpa";
    int i = 1;
}
<link rel="stylesheet" href="~/css/Korpa.css" />

@if (TempData["message"] != null)
{
    <div class="col-sm-12 text-center">
        <div class="alert alert-danger">
            @TempData["message"]
        </div>
    </div>
}

@if (Model.StripoviuKorpi.Any())
{
    <div class="table-container">
        <table class="table table-bordered table-dark">
            <thead>
                <tr>
                    <th scope="col">Br.</th>
                    <th scope="col">Strip</th>
                    <th scope="col">Naslov</th>
                    <th scope="col">Izdavac</th>
                    <th scope="col">Stanje</th>
                    <th scope="col">God. Izdanja</th>
                    <th scope="col">Jezik</th>
                    <th scope="col">Cena</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.StripoviuKorpi)
                {
                    var photoPath = "~/images/" + (item.imgRoute ?? "noimage.jpg");
                    <tr>
                        <td>@Convert.ToString(i++)</td>
                        <td><img src="@photoPath" alt="" asp-append-version="true"></td>
                        <td>@item.Naziv "@item.Naslov"</td>
                        <td>@item.Izdavac</td>
                        <td>@item.Stanje</td>
                        <td>@item.GodinaIzdanja</td>
                        <td>@item.Jezik</td>
                        <td>@item.Cena</td>
                        <td>
                            <form method="post" asp-page-handler="Obrisi">
                                <input hidden asp-for="IdStripaObrisi" value="@item.Id" />
                                <button type="submit" class="btn btn-danger">
                                    <svg width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                    </svg>
                                </button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="ukupno-container">
        <p>Ukupna cena: <span>@Model.UkupnaCena</span>din</p>
    </div>
    <form method="post" asp-page-handler="Potvrdi">
        <div class="adresa-container">
            <h4>Adresa isporuke</h4>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="@Model.BuyConfirmed.Grad"></label>
                    <input asp-for="@Model.BuyConfirmed.Grad" class="form-control" />
                    <span asp-validation-for="@Model.BuyConfirmed.Grad" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="@Model.BuyConfirmed.PostanskiBroj"></label>
                    <input asp-for="@Model.BuyConfirmed.PostanskiBroj" class="form-control" />
                    <span asp-validation-for="@Model.BuyConfirmed.PostanskiBroj" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="@Model.BuyConfirmed.Ulica"></label>
                    <input asp-for="@Model.BuyConfirmed.Ulica" class="form-control" />
                    <span asp-validation-for="@Model.BuyConfirmed.Ulica" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="@Model.BuyConfirmed.KucniBroj"></label>
                    <input asp-for="@Model.BuyConfirmed.KucniBroj" class="form-control" />
                    <span asp-validation-for="@Model.BuyConfirmed.KucniBroj" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="placanje-container">
            <h4>Placanje</h4>
            <select asp-for="BuyConfirmed.Placanje" class="form-group col-md-12" >
                <option value="Karticom">Placanje pouzecem</option>
                <option value="Pouzecem">Platnom karticom</option>
                <option value="Uplatnica">Placanje uplatnicom</option>
            </select>
        </div>
        <div class="pitanje-container">
            <h4>Imate pitanje?</h4>
            <textarea class="form-group col-md-12" id="message" asp-for="BuyConfirmed.Pitanje" placeholder="Pitanje"></textarea>
        </div>
        <div class="sazetak-container">
            <ul>
                <li><h4>Ukupno za placanje:</h4></li>
                <li>Ukupno: @Model.UkupnaCena din</li>
                <li>Usteda: 0din</li>
                <li>Troskovi dostave: Besplatni troskovi dostave</li>
                <li><span>Ukupno za placanje sa PDV-om:</span> @Model.UkupnaCena din</li>
            </ul>
        </div>
        <div class="checkbox-container">
            <label asp-for="BuyConfirmed.SlozenSaUslovima">
                <input asp-for="BuyConfirmed.SlozenSaUslovima" />
                Klikom na dugme, slažeš se sa Uslovima korišćenja i prodaje.
            </label>
            <span asp-validation-for="BuyConfirmed.SlozenSaUslovima" class="text-danger"></span>
        </div>
        @foreach (var item in Model.StripoviuKorpi)
        {
            <input hidden asp-for="BuyConfirmed.IdPorucenihStripova" value="@item.IdStripa" />
        }
        <input hidden asp-for="BuyConfirmed.UkupnaCena" value="@Model.UkupnaCena" />
        <div class="btn-container">
            <button type="submit" class="btn-action">Potvrdi</button>
        </div>
    </form>
}
else
{
    <p>Nema stripova u korpi</p>
}